# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fde269ae4a7f92eac3e47f631e08701d9d0cface8b84091b97088e958c9aa0499c14fb9b0b02671566634b9a41484e0c34dae24c16c6459a5045b7bc2515767e

test:
  secret_key_base: 88baba304a652d3fbbd215403c8e884bdfd228fa620f41970c4d1d217e6880dbca957b4939239b6fcca9486b67a4eb35819557f115f58753362ce4f4b9594fcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
